spring:
  application:
    name: maochd-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&useSSl=false
    username: root
    password: root

server:
  port: 8080
  servlet:
    context-path: /security
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml

